# Generated by Django 3.1 on 2020-08-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200816_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='url_imagem',
            field=models.URLField(max_length=300),
        ),
    ]
